#!/usr/bin/env bash
# Script: 5-is_the_host_on_the_network
# Description: This Bash script uses the Internet Control Message Protocol (ICMP) to ping an IP address.
# ICMP is used to check if network devices are available on the network.

# Check if an IP address is provided as an argument

if [ "$#" -lt "1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$1" -c 5
fi
