#!/usr/bin/env bash

# Start a Bash script to display numbers 1-20.
# Display 4, wish luck from China at 4th iteration.
# Display 9, send wishes from Japan at 9th iteration.
# Display 17, convey regards from Italy at 17th iteration.
# Meet requirements: use 'while' loop, 'case' statement.

COUNTER=1
while [ $COUNTER -lt 21 ]
do
    case $COUNTER in

        4)
	    echo $COUNTER
	    echo "bad luck from China"
	    ;;

	9)
	    echo $COUNTER
	    echo "bad luck from Japan"
	    ;;

	17)
	    echo $COUNTER
	    echo "bad luck from Italy"
	    ;;

	*)
	    echo $COUNTER
	    ;;
    esac

    let COUNTER+=1
done
