#!/usr/bin/env bash

# Start a Bash script to display numbers 1-20.
# Display 4, wish luck from China at 4th iteration.
# Display 9, send wishes from Japan at 9th iteration.
# Display 17, convey regards from Italy at 17th iteration.
# Meet requirements: use 'while' loop, 'case' statement.

i=1

while [ $i -le 20 ]
do
  echo "$i"
  case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( i++ ))
done
