#!/usr/bin/env bash
# Display directory contents in list format.
# Show only the part after the first dash in each name.
# Customized directory listing script.

if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
